### PR TITLE
Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by fredden**
Fixes https://github.com/Ethan3600/magento2-CronjobManager/issues/205

### CODE REVIEW

**Comment by fredden** [comment]
I expect the tests to pass here after https://github.com/extdn/github-actions-m2/pull/112 gets merged in and Magento 2.4.7 is released.

**Comment by peterjaap** [comment]
@Ethan3600 could you re-run the tests and if they succeed, merge this MR?

**Comment by fredden** [comment]
@peterjaap I've re-run this job: https://github.com/Ethan3600/magento2-CronjobManager/actions/runs/8394576024/job/23246115732?pr=206
It's still failing because Magento v2.4.7 hasn't been released yet. According to https://devdocs.magento.com/release/, it should be out in ~12 days. I've put a note in my calendar to come back here and re-run the tests then.

**Comment by peterjaap** [comment]
@fredden 2.4.7 is released :)

**Comment by fredden** [comment]
Magento v2.4.7 has been released. I have re-run all the tests here. Some tests are failing, but nothing seems related to PHP 8.3. I'll merge this in now (and tag a release), and review the test failures separately.

**Comment by peterjaap** [comment]
Awesome, thanks for the swift response! :partying_face:

**Pull request merged**
