### PR TITLE
Create console command for killing jobs

### PR DESCRIPTION
**Pull request by Ethan3600**
## Kill Job CLI

Creates CLI tool to kill one or more processes for a given job_code

### Screenshot

image

### CODE REVIEW

**Comment by schmengler** [comment]
Thanks for starting to work on this! How can I help you here? Looks like there are issues with the unit test setup?

**Comment by Ethan3600** [comment]
Hey @schmengler! Yeah I was trying to setup some unit tests and for some reason travis ci doesn't pick up the Tests/Unit/ directory. I was troubleshooting it over the weekend, and I ran `ls -laR vendor/$COMPOSER_PACKAGE_NAME/Test/` inside the before_script.sh file to see if the Unit/ directory REALLY wasn't there. And sure enough, when we deploy to Travis, it's not on their build environment for some reason. Haven't figured out why yet.

I wonder if it has to be inside the 1.x-develop branch first? That would seem very strange to me, but :man_shrugging: I'm at a loss at this point.

**Comment by schmengler** [comment]
> I wonder if it has to be inside the 1.x-develop branch first

Yes, but I found out why and fixed it in #124 (could not push directly into this branch)

**Comment by Ethan3600** [comment]
Figured out why integration tests were failing:

During the setup:install process the list of CLI commands is called. One of these commands has a dependency on the StoreManagerInterface. This tries to fetch from the database from its constructor which causes an error during integration tests because the table hasn't been created yet. Adding a proxy delays this call to the DB until it is used.

So, in this case `StoreManagementInterface` relies on a dependency the loads the StoreManagerInterface, so I added `\Proxy` at the end of the namespace to avoid the call to the DB.

Very odd, but at least now we can enjoy using Unit tests (looooong overdue).

**Comment by schmengler** [comment]
Good find, and yes, all the commands are always instantiated quite early, so using Proxies for their dependencies is generally a good practice

**Comment by Ethan3600** [comment]
Looks like the PR travis CI test is failing b/c it's trying to test 1.x-develop for unit tests that do not exist (yet)... Maybe we only need to test push. Need to explore this a little more.

Edit:

Seems like we're missing the phpunit.xml.dist config file.. but it's in the [merge](https://github.com/Ethan3600/magento2-CronjobManager/commit/cac7630822ea5e09445547daf0fbb3e053d113a5)

```bash
cp: cannot stat ‘vendor/ethanyehuda/magento2-cronjobmanager/Test/Unit/phpunit.xml.dist’: No such file or directory
Error: Command `cp vendor/$COMPOSER_PACKAGE_NAME/Test/Unit/phpunit.xml.dist dev/tests/unit/phpunit.xml` on line 57 failed with exit code 1
The command "./.travis/before_script.sh" failed and exited with 1 during .
```

**Comment by Ethan3600** [comment]
Going to disable Pull Request builds on travis.. there's all kinds of problems with getting the correct merge sha and I think push builds are enough anyway. Going to merge after the next successful push build.

**Pull request merged**
