### PR TITLE
64 static content deploy 404

### LINKED ISSUE #64: After installation, the static files are not being built correctly 404
Hi Ethen
The module looks great!!

I get this issue:
After installation, the static files are not being built correctly.
**Its building:**
pub/static/adminhtml/Magento/backend/en_US/EthanYehuda_CronjobManager/template..
**and looking for:**
pub/static/adminhtml/Magento/backend/en_US/cronjobManager/template..

I get 404 on the html requests

### PR DESCRIPTION
**Pull request by kirkmadera**
Removed template alias because Magento production mode does not respect it.

Fixes #64

### CODE REVIEW

**Comment by Ethan3600** [comment]
@kirkmadera Thanks for the contribution! Good catch!

Going to take a look at this as soon as possible.

**Comment by Ethan3600** [comment]
Can you change the base to 1.x-develop?

**Comment by kirkmadera** [comment]
Sure. Will try to get to this today. I'll do for the other PR for #70 also

**Comment by kirkmadera** [comment]
Thanks for the work on this module btw. This is filling the gap for Aoe_Scheduler not existing in M2.

**Comment by Ethan3600** [comment]
I'm glad it's helpful :) 

I changed the base branch of this PR for you. If you can rebase out the merge commits out, I'll go ahead and merge it.

**Comment by kirkmadera** [comment]
Rebuilt PR from 1.x-develop

**Comment by kirkmadera** [comment]
@Ethan3600 if you're interested, message me on Twitter @aredamkrik. We've got a lot of new work coming in at Robofirm and are looking for help. We do mostly Magento 2 work, are getting into some React/Vue Storefront work, and are also working on an open source tool called [Conductor](https://github.com/conductorphp) that handles deployments and syncing of lower environments.

**Comment by Ethan3600** [comment]
Thanks @kirkmadera I'll follow you on twitter!

Nice! I'll check Conductor out!

**Comment by kirkmadera** [comment]
It's still essentially internal. We have a few additional features to push out before flagging it as 1.0. It's stable internally though and is what we use to manage deployments everywhere. You'll hear about it through Twitter probably when we officially market it as open source for others to start using.

**Pull request merged**
