### PR TITLE
Fix PHP Fatal error on invalid job_code

### PR DESCRIPTION
**Pull request by fredden**
When running `bin/magento cronmanager:runjob no_such_job` the following error is encountered: 
>Fatal error: Uncaught TypeError: Return value of EthanYehuda\CronjobManager\Model\ScheduleManagement::getGroupId() must be of the type string, null returned in /var/www/html/vendor/ethanyehuda/magento2-cronjobmanager/Model/ScheduleManagement.php:112

This is because the return type declaration for `EthanYehuda\CronjobManager\Model\ScheduleManagement::getGroupId()` does not permit `null` to be returned. This pull request replaces the invalid return with an exception which can be caught as needed.

### CODE REVIEW

**Comment by Ethan3600** [comment]
Nice catch @fredden! I was wondering, rather than throwing an exception, could we instead make the return type [nullable](https://www.php.net/manual/en/migration71.new-features.php)? So, like: 

```php
 public function getGroupId(string $jobCode, $groups = null): ?string
```

Otherwise, we should probably go back and add some try/catch blocks in some of these files: https://github.com/Ethan3600/magento2-CronjobManager/search?q=getGroupId&unscoped_q=getGroupId

**Comment by fredden** [comment]
Yes, making the return type nullable is another way to avoid the TypeError, however we then have a PHP Notice (undefined index) (which Magento treats as fatal) on the following line.

https://github.com/Ethan3600/magento2-CronjobManager/blob/6360f59d9d533e544ce10fe9ab520e1f5c817795/Model/ScheduleManagement.php#L60-L61

The code-path taken with the example command already has a try/catch.

https://github.com/Ethan3600/magento2-CronjobManager/blob/6360f59d9d533e544ce10fe9ab520e1f5c817795/Model/Cron/Runner.php#L40-L42

There are no failures reported by the test-suite because of this change. Is there a particular code-path that needs better test coverage? I can possibly look into covering that and adding a try/catch if required.

**Comment by Ethan3600** [comment]
I wouldn't go down that rabbit hole regarding coverage. This project doesn't have the best coverage because when I started it, I didn't know the first thing about testing. I think what you're saying makes sense. Ideally, we change `$groups[$groupId][$jobCode]` to `$groups[$groupId][$jobCode] ?? null` or something, but I agree with your solution.

We just need to account for unhandled exceptions where we use this method by throwing a try/catch in there wherever we use `getGroupId`.

**Comment by fredden** [comment]
I've reviewed possible code paths that lead to this new exception.
- `Api::ScheduleManagementInterface::getGroupId()` - I have updated the docblock to correct the return type and show an exception can be thrown here.
- `Helper\JobConfig::constructFrequencyPath()` - If `getGroupId()` returns a falsy value an exception is thrown. I suggest leaving this without a try/catch. What do you recommend here?
- `Model\Manager::getGroupId()` - This method is only used in `Helper\JobConfig::constructFrequencyPath()` - see above.
- `Model\ScheduleManagement::execute()` - This is called in:
  - `Model\Cron\Runner::runCron()` - already wrapped in try/catch
  - `Model\Manager::dispatchCron()` - This method is only used in `Controller\Adminhtml\Manage\Job\Dispatch::execute()` which is wrapped in a try/catch already.
  - `Model\Manager::dispatchSchedule()` - This method is only used in `Controller\Adminhtml\Manage\Job\MassDispatch::execute()` which is wrapped in a try/catch already.

Are there any other code paths that I've missed?

**Comment by Ethan3600** [comment]
I think that about covers it! (You've given me a lot of homework to do :smile:! These are tremendous contributions!) As per:

* _Helper\JobConfig::constructFrequencyPath() - If getGroupId() returns a falsy value an exception is thrown. I suggest leaving this without a try/catch_

I think you're right, we should leave it as is.

Before I merge this, I'll focus on the PR to fix the unit tests: https://github.com/Ethan3600/magento2-CronjobManager/pull/143

Let's try to get Travis to green!

**Review by Ethan3600 — APPROVED** [review]

**Comment by Ethan3600** [comment]
I figure this is the next thing we want to get merged. Looks like there's a merge conflict. Once that's cleared, let's merge this!

**Review by Ethan3600 — APPROVED** [review]

**Pull request merged**
