### PR TITLE
Fix command error 'area is already set'

### PR DESCRIPTION
**Pull request by haelbichalex**
Magento 2.2.5

Running the `cronjobmanager:showjobs` task I got the error `area code is already set`. PR fixed it for me.

### CODE REVIEW

**Comment by Ethan3600** [comment]
Thanks for contributing @haelbichalex! 

I changed the base to 1.x-develop. Could you please rebase those extra merge commits out?

**Comment by haelbichalex** [comment]
Hi @Ethan3600.
I'm quite new to the pull request workflow, so I think I messed up this one 😓 
How can I rebase my branch?

**Comment by Ethan3600** [comment]
That's ok :laughing: It's partly my fault because I should create a better contribution guideline, but I just haven't found time for it. The idea is to branch off 1.x-develop and contribute from there. But most (if not all) contributors branch off 1.x. Just bad documentation I guess.

That leaves us with two options:

1) learn how to rebase properly (harder, but great to know how to do!)

* https://www.youtube.com/watch?v=6EiI5XgtvFU

* https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

* The goal here is to remove all the commits that you didn't create

2) Close this PR and open a new PR where you branched off 1.x-develop (easier)

* you'd just have to re-add your commits on top of 1.x-develop

-------

I'll leave this up to you! Let me know if I can do anything else to help.

Thanks again for the contribution

**Comment by haelbichalex** [comment]
Thank you for sharing the tips!
I did choose option 2 though, to make sure everything's cleaned up. #77

**Pull request closed without merging**
